name: Deploying on self-hosted runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy docker-compose on host
    runs-on: [self-hosted, Linux] 
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Verify Docker Compose
        run: docker --version

      - name: Run Docker Compose
        run: |  
          cd /home/devteam/frontend
          git pull origin main
          docker compose up -d --buid --remove-orphans